-- Limpieza de datos previos
TRUNCATE ingredientes, recetas, receta_ingredientes, planificacion CASCADE;

-- Insertar Ingredientes
INSERT INTO ingredientes (nombre, categoria) VALUES ('Guisantes', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Zanahoria', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Espinacas', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Huevo', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Lentejas', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Ternera', '🥩 Carnicería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Cerdo', '🥩 Carnicería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Filetes De Cerdo', '🥩 Carnicería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Judias Verdes', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Pavo', '🥩 Carnicería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Salchichas', '🥩 Carnicería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Arroz', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Yogurt', '🥛 Frescos') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Suavizante', '🧼 Limpieza') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Detergente De Lavadora', '🧼 Limpieza') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Detergente De Lavavajillas', '🧼 Limpieza') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Abrillantador De Lavavajillas', '🧼 Limpieza') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Sal', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Azucar', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Aceite', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Soja', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Fruta', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Kiwi', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Manzana', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Embutido', '🥩 Carnicería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Hamburguesa', '🥩 Carnicería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Pan Hamburguesa', '🥖 Panadería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Lechuga', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Cebolla', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Oregano', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Perejil', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Talco', 'Otros') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Champu', '🧼 Limpieza') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Leche', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Mermelada', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Mantequilla', '🥛 Frescos') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Pan', '🥖 Panadería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Costillas', '🥩 Carnicería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Criollos', '🥩 Carnicería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Sandia', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Garbanzos', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Vinagre', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Vinagre De Arroz', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Alga Nori', 'Otros') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Arroz Sushi', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Pimiento', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Colorante Alimenticio', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Taquitos De Jamon', '🧀 Charcuteria') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Proteinas En Polvo', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Tomate', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Jamón Serrano', '🥩 Carnicería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Bolsas De Basura', 'Otros') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Pan avena o centeno', '🥖 Panadería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Cafe', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Fajitas', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Pollo', '🥩 Carnicería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Aguacate', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Canonigos', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Carne picada', '🥩 Carnicería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Tomate frito', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Patata', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Merluza', '🐟 Pescaderia') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Agua', '🥦 Frutería') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ingredientes (nombre, categoria) VALUES ('Sopa de sobre', '🥫 Despensa') ON CONFLICT (nombre) DO NOTHING;

-- Insertar Recetas
INSERT INTO recetas (nombre) VALUES ('Arroz con pavo') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Arroz con salchichas') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Compra') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Estofado de Lentejas') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Batido Proteinas') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Tostada con jamón y tomate') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Tosta con aceite y embutido') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Cafe con fruta') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Fajitas de pollo') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Muslitos de pollo') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Ensalada lechuga y canonigos') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Pasta con carne') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Merluza a la plancha con patatas y ensalada') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Tostada con embutido') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO recetas (nombre) VALUES ('Sopa con huevo') ON CONFLICT (nombre) DO NOTHING;

-- Insertar Relaciones Receta-Ingrediente
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con salchichas' AND i.nombre = 'Arroz' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con salchichas' AND i.nombre = 'Espinacas' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con salchichas' AND i.nombre = 'Guisantes' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con salchichas' AND i.nombre = 'Judias Verdes' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con salchichas' AND i.nombre = 'Salchichas' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con salchichas' AND i.nombre = 'Zanahoria' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Estofado de Lentejas' AND i.nombre = 'Lentejas' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Estofado de Lentejas' AND i.nombre = 'Espinacas' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Estofado de Lentejas' AND i.nombre = 'Cebolla' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Estofado de Lentejas' AND i.nombre = 'Pimiento' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Estofado de Lentejas' AND i.nombre = 'Taquitos De Jamon' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Estofado de Lentejas' AND i.nombre = 'Zanahoria' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Estofado de Lentejas' AND i.nombre = 'Judias Verdes' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Estofado de Lentejas' AND i.nombre = 'Aceite' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Batido Proteinas' AND i.nombre = 'Proteinas En Polvo' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Tostada con jamón y tomate' AND i.nombre = 'Tomate' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Tostada con jamón y tomate' AND i.nombre = 'Jamón Serrano' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Tostada con jamón y tomate' AND i.nombre = 'Aceite' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Tosta con aceite y embutido' AND i.nombre = 'Aceite' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Tosta con aceite y embutido' AND i.nombre = 'Embutido' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Tosta con aceite y embutido' AND i.nombre = 'Pan avena o centeno' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Cafe con fruta' AND i.nombre = 'Kiwi' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Cafe con fruta' AND i.nombre = 'Cafe' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Fajitas de pollo' AND i.nombre = 'Pimiento' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Fajitas de pollo' AND i.nombre = 'Aguacate' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Fajitas de pollo' AND i.nombre = 'Cebolla' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Fajitas de pollo' AND i.nombre = 'Fajitas' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Fajitas de pollo' AND i.nombre = 'Pollo' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Muslitos de pollo' AND i.nombre = 'Pollo' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Ensalada lechuga y canonigos' AND i.nombre = 'Lechuga' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Ensalada lechuga y canonigos' AND i.nombre = 'Canonigos' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Pasta con carne' AND i.nombre = 'Carne picada' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Pasta con carne' AND i.nombre = 'Tomate frito' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Pasta con carne' AND i.nombre = 'Cebolla' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Merluza a la plancha con patatas y ensalada' AND i.nombre = 'Lechuga' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Merluza a la plancha con patatas y ensalada' AND i.nombre = 'Canonigos' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Merluza a la plancha con patatas y ensalada' AND i.nombre = 'Merluza' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Merluza a la plancha con patatas y ensalada' AND i.nombre = 'Patata' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Tostada con embutido' AND i.nombre = 'Pan' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Tostada con embutido' AND i.nombre = 'Embutido' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con pavo' AND i.nombre = 'Guisantes' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con pavo' AND i.nombre = 'Zanahoria' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con pavo' AND i.nombre = 'Espinacas' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con pavo' AND i.nombre = 'Judias Verdes' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con pavo' AND i.nombre = 'Pavo' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con pavo' AND i.nombre = 'Arroz' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con pavo' AND i.nombre = 'Pimiento' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Arroz con pavo' AND i.nombre = 'Colorante Alimenticio' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Compra' AND i.nombre = 'Abrillantador De Lavavajillas' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Compra' AND i.nombre = 'Aceite' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Compra' AND i.nombre = 'Leche' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Compra' AND i.nombre = 'Agua' ON CONFLICT DO NOTHING;
INSERT INTO receta_ingredientes (receta_id, ingrediente_id) SELECT r.id, i.id FROM recetas r, ingredientes i WHERE r.nombre = 'Sopa con huevo' AND i.nombre = 'Huevo' ON CONFLICT DO NOTHING;

-- Insertar Planificación
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-02', 'Media Mañana', id FROM recetas WHERE nombre = 'Batido Proteinas' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-03', 'Media Mañana', id FROM recetas WHERE nombre = 'Batido Proteinas' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-04', 'Media Mañana', id FROM recetas WHERE nombre = 'Batido Proteinas' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-03', 'Desayuno', id FROM recetas WHERE nombre = 'Tostada con jamón y tomate' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-03', 'Comida', id FROM recetas WHERE nombre = 'Estofado de Lentejas' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-04', 'Compra General', id FROM recetas WHERE nombre = 'Compra' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-02', 'Comida', id FROM recetas WHERE nombre = 'Estofado de Lentejas' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-02', 'Desayuno', id FROM recetas WHERE nombre = 'Tosta con aceite y embutido' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-04', 'Comida', id FROM recetas WHERE nombre = 'Arroz con pavo' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-05', 'Comida', id FROM recetas WHERE nombre = 'Arroz con pavo' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-05', 'Desayuno', id FROM recetas WHERE nombre = 'Cafe con fruta' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-05', 'Media Mañana', id FROM recetas WHERE nombre = 'Tosta con aceite y embutido' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-05', 'Media Tarde', id FROM recetas WHERE nombre = 'Tostada con jamón y tomate' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-05', 'Cena', id FROM recetas WHERE nombre = 'Fajitas de pollo' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-06', 'Desayuno', id FROM recetas WHERE nombre = 'Tostada con jamón y tomate' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-02', 'Media Tarde', id FROM recetas WHERE nombre = 'Tostada con jamón y tomate' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-02', 'Cena', id FROM recetas WHERE nombre = 'Muslitos de pollo' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-02', 'Compra General', id FROM recetas WHERE nombre = 'Ensalada lechuga y canonigos' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-03', 'Media Tarde', id FROM recetas WHERE nombre = 'Tostada con jamón y tomate' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-04', 'Media Tarde', id FROM recetas WHERE nombre = 'Tostada con jamón y tomate' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-05', 'Compra General', id FROM recetas WHERE nombre = 'Ensalada lechuga y canonigos' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-06', 'Comida', id FROM recetas WHERE nombre = 'Pasta con carne' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-07', 'Desayuno', id FROM recetas WHERE nombre = 'Cafe con fruta' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-08', 'Desayuno', id FROM recetas WHERE nombre = 'Cafe con fruta' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-09', 'Desayuno', id FROM recetas WHERE nombre = 'Cafe con fruta' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-06', 'Media Tarde', id FROM recetas WHERE nombre = 'Tostada con jamón y tomate' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-06', 'Cena', id FROM recetas WHERE nombre = 'Merluza a la plancha con patatas y ensalada' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-08', 'Comida', id FROM recetas WHERE nombre = 'Pasta con carne' ON CONFLICT (fecha, momento) DO NOTHING;
INSERT INTO planificacion (fecha, momento, receta_id) SELECT '2026-01-04', 'Cena', id FROM recetas WHERE nombre = 'Sopa con huevo' ON CONFLICT (fecha, momento) DO NOTHING;
